name: Build and Deploy to Github Pages

on:
  push:
    branches:
      - dev  # Here source code branch is `master`, it could be other branch
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: 'Wait for status checks'
        id: waitforstatuschecks
        uses: "WyriHaximus/github-action-wait-for-status@v1.2"
        with:
          ignoreActions: build_and_deploy
          checkInterval: 10
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Clean install dependencies and build
        run: |
          sudo apt-get update && sudo apt-get install -y libvips42

      - uses: actions/checkout@v2
        with:
          fetch-depth: zero

      # Use GitHub Actions' cache to cache dependencies on servers
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      # Use GitHub Actions' cache to cache site on servers
      - uses: actions/cache@v2
        with:
          path: build
          key: ${{ runner.os }}-build-${{ hashFiles('**/_data/picture.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-

      # Use GitHub Deploy Action to build and deploy to Github
      - uses: jeffreytse/jekyll-deploy-action@master
        with:
          provider: 'github'
          token: ${{ secrets.GH_TOKEN }} # It's your Personal Access Token(PAT)
          repository: 'datapolitical/cfndev.github.io'             # Default is current repository
          branch: 'gh-pages'         # Default is gh-pages for github provider
          jekyll_src: './'           # Default is root directory
          jekyll_cfg: '_config.yml'  # Default is _config.yml
          jekyll_baseurl: '/cfndev.github.io'         # Default is according to _config.yml
          bundler_ver: '>=0'         # Default is latest bundler version
          cname: ''                  # Default is to not use a cname
          actor: ''                  # Default is the GITHUB_ACTOR
